# Generated by Django 4.1.3 on 2022-11-11 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("registers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="End date"
                    ),
                ),
                ("balance", models.FloatField(verbose_name="Balance brought forward")),
                ("final_balance", models.FloatField(verbose_name="Final balance")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registers.register",
                        verbose_name="Full name",
                    ),
                ),
            ],
        ),
    ]
