# Generated by Django 4.1.3 on 2022-11-01 15:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=250, verbose_name="Enter Full Name"),
                ),
                ("cni_no", models.IntegerField(unique=True)),
                (
                    "rent_type",
                    models.CharField(
                        choices=[
                            ("chambre", "chambre"),
                            ("studio", "studio"),
                            ("appartement", "appartement"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "address",
                    models.CharField(max_length=150, verbose_name="Street address"),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Start date"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Amount paid")),
            ],
        ),
    ]
